language: node_js

env:
  - TARGET=test

node_js:
  - '6'
  - '8.7.0'
  - '9'
  - '10'

matrix:
  include:
  - name: Lint
    node_js: '8.7.0'
    env:
      - TARGET=lint
  - name: Coverage
    node_js: '8.7.0'
    env:
      - TARGET=coverage
  - name: BrowserStack IE11
    node_js: '8.7.0'
    env:
      - TARGET=test-browser
      - BROWSER=ie11
  - name: Chrome headless
    node_js: '8.7.0'
    env:
      - TARGET=test-browser
      - BROWSER=ChromeHeadless

addons:
  chrome: stable

script: npm run $TARGET

after_success: '<coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js'
