services:
  - docker
sudo: required
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '6'
  - '8'
  - '10'
  - 'node'

addons:
  chrome: stable
  apt:
    packages:
      - gcc-4.8
      - g++-4.8
env: CXX="g++-4.8" CC="gcc-4.8"

script: 'npm run ci'
after_success: '<coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js'

# jsdom 3.x fails on these, but jsdom 4.x+ fails on those below :(((
matrix:
  allow_failures:
    - node_js: '3'
    - node_js: '4'
  include:
  - name: BrowserStack IE11
    node_js: '8'
    env: BROWSER=ie11
  - name: Chrome headless
    node_js: "8"
    env: BROWSER=ChromeHeadless
